//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDMS.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string AccountID {
            get {
                return ResourceManager.GetString("AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳款月份 的當地語系化字串。
        /// </summary>
        public static string AccountMonth {
            get {
                return ResourceManager.GetString("AccountMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戶名 的當地語系化字串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住址 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 調整數量 的當地語系化字串。
        /// </summary>
        public static string Adjust {
            get {
                return ResourceManager.GetString("Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品 的當地語系化字串。
        /// </summary>
        public static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品數量 的當地語系化字串。
        /// </summary>
        public static string AlternativeCount {
            get {
                return ResourceManager.GetString("AlternativeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品編號 的當地語系化字串。
        /// </summary>
        public static string AlternativeID {
            get {
                return ResourceManager.GetString("AlternativeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品名稱 的當地語系化字串。
        /// </summary>
        public static string AlternativeName {
            get {
                return ResourceManager.GetString("AlternativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額 的當地語系化字串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度責任金額 的當地語系化字串。
        /// </summary>
        public static string AnnualTarget {
            get {
                return ResourceManager.GetString("AnnualTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核人 的當地語系化字串。
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期餘額 的當地語系化字串。
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 託收(存入)銀行帳號 的當地語系化字串。
        /// </summary>
        public static string BankAccountID {
            get {
                return ResourceManager.GetString("BankAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銀行編號 的當地語系化字串。
        /// </summary>
        public static string BankID {
            get {
                return ResourceManager.GetString("BankID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銀行名稱 的當地語系化字串。
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號啟用日期 的當地語系化字串。
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務成本 的當地語系化字串。
        /// </summary>
        public static string BizCost {
            get {
                return ResourceManager.GetString("BizCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料清單(BOM) 的當地語系化字串。
        /// </summary>
        public static string BOM {
            get {
                return ResourceManager.GetString("BOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠牌編碼 的當地語系化字串。
        /// </summary>
        public static string BrandID {
            get {
                return ResourceManager.GetString("BrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠牌名稱 的當地語系化字串。
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品設定 的當地語系化字串。
        /// </summary>
        public static string ButtonAlternative {
            get {
                return ResourceManager.GetString("ButtonAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核 的當地語系化字串。
        /// </summary>
        public static string ButtonAudit {
            get {
                return ResourceManager.GetString("ButtonAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批次新增 的當地語系化字串。
        /// </summary>
        public static string ButtonBatchCreate {
            get {
                return ResourceManager.GetString("ButtonBatchCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案 的當地語系化字串。
        /// </summary>
        public static string ButtonCloseCase {
            get {
                return ResourceManager.GetString("ButtonCloseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出 的當地語系化字串。
        /// </summary>
        public static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片上傳 的當地語系化字串。
        /// </summary>
        public static string ButtonImage {
            get {
                return ResourceManager.GetString("ButtonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護 的當地語系化字串。
        /// </summary>
        public static string ButtonModify {
            get {
                return ResourceManager.GetString("ButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定過帳 的當地語系化字串。
        /// </summary>
        public static string ButtonPosting {
            get {
                return ResourceManager.GetString("ButtonPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對帳明細表 的當地語系化字串。
        /// </summary>
        public static string ButtonReceivableDetail {
            get {
                return ResourceManager.GetString("ButtonReceivableDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對帳單 的當地語系化字串。
        /// </summary>
        public static string ButtonReconciliation {
            get {
                return ResourceManager.GetString("ButtonReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存檔 的當地語系化字串。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品 的當地語系化字串。
        /// </summary>
        public static string ButtonShowAlternative {
            get {
                return ResourceManager.GetString("ButtonShowAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統計表匯出 的當地語系化字串。
        /// </summary>
        public static string ButtonStatistics {
            get {
                return ResourceManager.GetString("ButtonStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢視 的當地語系化字串。
        /// </summary>
        public static string ButtonView {
            get {
                return ResourceManager.GetString("ButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 現金金額 的當地語系化字串。
        /// </summary>
        public static string CashAmount {
            get {
                return ResourceManager.GetString("CashAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動日期 的當地語系化字串。
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經手人 的當地語系化字串。
        /// </summary>
        public static string ChangePersonID {
            get {
                return ResourceManager.GetString("ChangePersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改人 的當地語系化字串。
        /// </summary>
        public static string ChangePersonName {
            get {
                return ResourceManager.GetString("ChangePersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動原因 的當地語系化字串。
        /// </summary>
        public static string ChangeReason {
            get {
                return ResourceManager.GetString("ChangeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動原因 的當地語系化字串。
        /// </summary>
        public static string ChangeReasonID {
            get {
                return ResourceManager.GetString("ChangeReasonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動原因 的當地語系化字串。
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支票金額 的當地語系化字串。
        /// </summary>
        public static string CheckAmount {
            get {
                return ResourceManager.GetString("CheckAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支票號碼 的當地語系化字串。
        /// </summary>
        public static string CheckNum {
            get {
                return ResourceManager.GetString("CheckNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 票據狀況 的當地語系化字串。
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務員 的當地語系化字串。
        /// </summary>
        public static string Clerk {
            get {
                return ResourceManager.GetString("Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務員手機 的當地語系化字串。
        /// </summary>
        public static string ClerkMobile {
            get {
                return ResourceManager.GetString("ClerkMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代碼名稱 的當地語系化字串。
        /// </summary>
        public static string CodeName {
            get {
                return ResourceManager.GetString("CodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代碼類別 的當地語系化字串。
        /// </summary>
        public static string CodeType {
            get {
                return ResourceManager.GetString("CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代碼值 的當地語系化字串。
        /// </summary>
        public static string CodeValue {
            get {
                return ResourceManager.GetString("CodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司編號 的當地語系化字串。
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商類別 的當地語系化字串。
        /// </summary>
        public static string CompanyKindID {
            get {
                return ResourceManager.GetString("CompanyKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商全稱 的當地語系化字串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶廠商 的當地語系化字串。
        /// </summary>
        public static string CompanySupplier {
            get {
                return ResourceManager.GetString("CompanySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件 的當地語系化字串。
        /// </summary>
        public static string ConditionID {
            get {
                return ResourceManager.GetString("ConditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人 的當地語系化字串。
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話 的當地語系化字串。
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別 的當地語系化字串。
        /// </summary>
        public static string CurrencyID {
            get {
                return ResourceManager.GetString("CurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶編號 的當地語系化字串。
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶名稱 的當地語系化字串。
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生日 的當地語系化字串。
        /// </summary>
        public static string CX_Birthday {
            get {
                return ResourceManager.GetString("CX_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顏色 的當地語系化字串。
        /// </summary>
        public static string CX_Color {
            get {
                return ResourceManager.GetString("CX_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 記錄內容 的當地語系化字串。
        /// </summary>
        public static string CX_Content {
            get {
                return ResourceManager.GetString("CX_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國家 的當地語系化字串。
        /// </summary>
        public static string CX_Country {
            get {
                return ResourceManager.GetString("CX_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國別備註 的當地語系化字串。
        /// </summary>
        public static string CX_Country_Remarks {
            get {
                return ResourceManager.GetString("CX_Country_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        public static string CX_Date {
            get {
                return ResourceManager.GetString("CX_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理方式 的當地語系化字串。
        /// </summary>
        public static string CX_DealWith {
            get {
                return ResourceManager.GetString("CX_DealWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string CX_Dept_Name {
            get {
                return ResourceManager.GetString("CX_Dept_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回饋屬性備註 的當地語系化字串。
        /// </summary>
        public static string CX_Feeback_Remarks {
            get {
                return ResourceManager.GetString("CX_Feeback_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回饋屬性 的當地語系化字串。
        /// </summary>
        public static string CX_Feedback {
            get {
                return ResourceManager.GetString("CX_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出發日期 的當地語系化字串。
        /// </summary>
        public static string CX_From_Date {
            get {
                return ResourceManager.GetString("CX_From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組別 的當地語系化字串。
        /// </summary>
        public static string CX_Group_Name {
            get {
                return ResourceManager.GetString("CX_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建議改善 的當地語系化字串。
        /// </summary>
        public static string CX_Improve {
            get {
                return ResourceManager.GetString("CX_Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string CX_Name {
            get {
                return ResourceManager.GetString("CX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 觀察構面 的當地語系化字串。
        /// </summary>
        public static string CX_Observation {
            get {
                return ResourceManager.GetString("CX_Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 觀察構面備註 的當地語系化字串。
        /// </summary>
        public static string CX_Observation_Remarks {
            get {
                return ResourceManager.GetString("CX_Observation_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到職日 的當地語系化字串。
        /// </summary>
        public static string CX_OnBoard_Date {
            get {
                return ResourceManager.GetString("CX_OnBoard_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出國備註 的當地語系化字串。
        /// </summary>
        public static string CX_OverSea_Remark {
            get {
                return ResourceManager.GetString("CX_OverSea_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差類別 的當地語系化字串。
        /// </summary>
        public static string CX_OverType {
            get {
                return ResourceManager.GetString("CX_OverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工號 的當地語系化字串。
        /// </summary>
        public static string CX_PID {
            get {
                return ResourceManager.GetString("CX_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地點備註 的當地語系化字串。
        /// </summary>
        public static string CX_Place_Remark {
            get {
                return ResourceManager.GetString("CX_Place_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string CX_Remark {
            get {
                return ResourceManager.GetString("CX_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料夾信箱 的當地語系化字串。
        /// </summary>
        public static string CX_Send_To_Mail {
            get {
                return ResourceManager.GetString("CX_Send_To_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門市 的當地語系化字串。
        /// </summary>
        public static string CX_Store_Name {
            get {
                return ResourceManager.GetString("CX_Store_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門市備註 的當地語系化字串。
        /// </summary>
        public static string CX_Store_Remarks {
            get {
                return ResourceManager.GetString("CX_Store_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string CX_Title {
            get {
                return ResourceManager.GetString("CX_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返台日期 的當地語系化字串。
        /// </summary>
        public static string CX_To_Date {
            get {
                return ResourceManager.GetString("CX_To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 後續追蹤狀況 的當地語系化字串。
        /// </summary>
        public static string CX_Track {
            get {
                return ResourceManager.GetString("CX_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 後續追蹤狀況備註 的當地語系化字串。
        /// </summary>
        public static string CX_Track_Remarks {
            get {
                return ResourceManager.GetString("CX_Track_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作崗位 的當地語系化字串。
        /// </summary>
        public static string CX_Workplace {
            get {
                return ResourceManager.GetString("CX_Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作崗位備註 的當地語系化字串。
        /// </summary>
        public static string CX_Workplace_Remarks {
            get {
                return ResourceManager.GetString("CX_Workplace_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收(開)票日期 的當地語系化字串。
        /// </summary>
        public static string DealDate {
            get {
                return ResourceManager.GetString("DealDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 交易項目 的當地語系化字串。
        /// </summary>
        public static string DealItem {
            get {
                return ResourceManager.GetString("DealItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 票面金額 的當地語系化字串。
        /// </summary>
        public static string DebitAmount {
            get {
                return ResourceManager.GetString("DebitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 抵扣金額 的當地語系化字串。
        /// </summary>
        public static string DeductAmount {
            get {
                return ResourceManager.GetString("DeductAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折數 的當地語系化字串。
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓金額 的當地語系化字串。
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折扣率 的當地語系化字串。
        /// </summary>
        public static string DiscountRate {
            get {
                return ResourceManager.GetString("DiscountRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案日期 的當地語系化字串。
        /// </summary>
        public static string DT_Close {
            get {
                return ResourceManager.GetString("DT_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理日期 的當地語系化字串。
        /// </summary>
        public static string DT_Process {
            get {
                return ResourceManager.GetString("DT_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到期日 的當地語系化字串。
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EMAIL帳號 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號停用日期 的當地語系化字串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯率 的當地語系化字串。
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到期日期 的當地語系化字串。
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工廠地址 的當地語系化字串。
        /// </summary>
        public static string FactoryAddress {
            get {
                return ResourceManager.GetString("FactoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳真機號碼 的當地語系化字串。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作簽 的當地語系化字串。
        /// </summary>
        public static string FG_IsWorkCard {
            get {
                return ResourceManager.GetString("FG_IsWorkCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外幣單價 的當地語系化字串。
        /// </summary>
        public static string ForeignPrice {
            get {
                return ResourceManager.GetString("ForeignPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商全稱 的當地語系化字串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 毛利率% 的當地語系化字串。
        /// </summary>
        public static string GrossProfitMargin {
            get {
                return ResourceManager.GetString("GrossProfitMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差國家 的當地語系化字串。
        /// </summary>
        public static string ID_Country {
            get {
                return ResourceManager.GetString("ID_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回饋屬性 的當地語系化字串。
        /// </summary>
        public static string ID_Feedback {
            get {
                return ResourceManager.GetString("ID_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 觀察構面 的當地語系化字串。
        /// </summary>
        public static string ID_Observation {
            get {
                return ResourceManager.GetString("ID_Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 種類 的當地語系化字串。
        /// </summary>
        public static string ID_OverType {
            get {
                return ResourceManager.GetString("ID_OverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string ID_Status {
            get {
                return ResourceManager.GetString("ID_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店別 的當地語系化字串。
        /// </summary>
        public static string ID_Store {
            get {
                return ResourceManager.GetString("ID_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 後續追蹤狀況 的當地語系化字串。
        /// </summary>
        public static string ID_Track {
            get {
                return ResourceManager.GetString("ID_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作崗位 的當地語系化字串。
        /// </summary>
        public static string ID_Workplace {
            get {
                return ResourceManager.GetString("ID_Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 改善圖片 的當地語系化字串。
        /// </summary>
        public static string Improve_Image {
            get {
                return ResourceManager.GetString("Improve_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 期初金額 的當地語系化字串。
        /// </summary>
        public static string InitialAmount {
            get {
                return ResourceManager.GetString("InitialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 期初日期 的當地語系化字串。
        /// </summary>
        public static string InitialDate {
            get {
                return ResourceManager.GetString("InitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詢價日期 的當地語系化字串。
        /// </summary>
        public static string InquiryDate {
            get {
                return ResourceManager.GetString("InquiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詢價單編號 的當地語系化字串。
        /// </summary>
        public static string InquiryID {
            get {
                return ResourceManager.GetString("InquiryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巡檢圖片 的當地語系化字串。
        /// </summary>
        public static string Inspection_Image {
            get {
                return ResourceManager.GetString("Inspection_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票地址 的當地語系化字串。
        /// </summary>
        public static string InvoiceAddress {
            get {
                return ResourceManager.GetString("InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票金額 的當地語系化字串。
        /// </summary>
        public static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票日期 的當地語系化字串。
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string InvoiceID {
            get {
                return ResourceManager.GetString("InvoiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票狀態 的當地語系化字串。
        /// </summary>
        public static string InvoiceStatusID {
            get {
                return ResourceManager.GetString("InvoiceStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品類別 的當地語系化字串。
        /// </summary>
        public static string KindID {
            get {
                return ResourceManager.GetString("KindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上期餘額 的當地語系化字串。
        /// </summary>
        public static string LastBalance {
            get {
                return ResourceManager.GetString("LastBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支票最後使用日期 的當地語系化字串。
        /// </summary>
        public static string LastDate {
            get {
                return ResourceManager.GetString("LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支票最後使用號碼 的當地語系化字串。
        /// </summary>
        public static string LastNumber {
            get {
                return ResourceManager.GetString("LastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新進貨成本 的當地語系化字串。
        /// </summary>
        public static string LatestCost {
            get {
                return ResourceManager.GetString("LatestCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務成本與銷售成本連動 的當地語系化字串。
        /// </summary>
        public static string Linked {
            get {
                return ResourceManager.GetString("Linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一筆 的當地語系化字串。
        /// </summary>
        public static string LinkToNextPageFormat {
            get {
                return ResourceManager.GetString("LinkToNextPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上一筆 的當地語系化字串。
        /// </summary>
        public static string LinkToPreviousPageFormat {
            get {
                return ResourceManager.GetString("LinkToPreviousPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 牌價 的當地語系化字串。
        /// </summary>
        public static string ListPrice {
            get {
                return ResourceManager.GetString("ListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 替代品資料維護 的當地語系化字串。
        /// </summary>
        public static string MenuAlternative {
            get {
                return ResourceManager.GetString("MenuAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BankAccount 的當地語系化字串。
        /// </summary>
        public static string MenuBankAccount {
            get {
                return ResourceManager.GetString("MenuBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差人員生日 的當地語系化字串。
        /// </summary>
        public static string MenuBirthday {
            get {
                return ResourceManager.GetString("MenuBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Brand 的當地語系化字串。
        /// </summary>
        public static string MenuBrand {
            get {
                return ResourceManager.GetString("MenuBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Code 的當地語系化字串。
        /// </summary>
        public static string MenuCode {
            get {
                return ResourceManager.GetString("MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company 的當地語系化字串。
        /// </summary>
        public static string MenuCompany {
            get {
                return ResourceManager.GetString("MenuCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差國別設定 的當地語系化字串。
        /// </summary>
        public static string MenuCountry {
            get {
                return ResourceManager.GetString("MenuCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Dynamic 的當地語系化字串。
        /// </summary>
        public static string MenuDynamic {
            get {
                return ResourceManager.GetString("MenuDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回饋屬性設定 的當地語系化字串。
        /// </summary>
        public static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歷史資料查詢 的當地語系化字串。
        /// </summary>
        public static string MenuHistory {
            get {
                return ResourceManager.GetString("MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inquiry 的當地語系化字串。
        /// </summary>
        public static string MenuInquiry {
            get {
                return ResourceManager.GetString("MenuInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人巡檢資料 的當地語系化字串。
        /// </summary>
        public static string MenuInspection {
            get {
                return ResourceManager.GetString("MenuInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巡檢報表 的當地語系化字串。
        /// </summary>
        public static string MenuInspectionReport {
            get {
                return ResourceManager.GetString("MenuInspectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巡檢報告 的當地語系化字串。
        /// </summary>
        public static string MenuInspectionReportD {
            get {
                return ResourceManager.GetString("MenuInspectionReportD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巡檢管理 的當地語系化字串。
        /// </summary>
        public static string MenuInspectionTop {
            get {
                return ResourceManager.GetString("MenuInspectionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新消息維護 的當地語系化字串。
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前出差海外人數表 的當地語系化字串。
        /// </summary>
        public static string MenuNowOverSea {
            get {
                return ResourceManager.GetString("MenuNowOverSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 觀察構面設定 的當地語系化字串。
        /// </summary>
        public static string MenuObservation {
            get {
                return ResourceManager.GetString("MenuObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差人員設定 的當地語系化字串。
        /// </summary>
        public static string MenuOverSea {
            get {
                return ResourceManager.GetString("MenuOverSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差人員顯示 的當地語系化字串。
        /// </summary>
        public static string MenuOverSeaDisplay {
            get {
                return ResourceManager.GetString("MenuOverSeaDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人員管理 的當地語系化字串。
        /// </summary>
        public static string MenuOverStaff {
            get {
                return ResourceManager.GetString("MenuOverStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差類別設定 的當地語系化字串。
        /// </summary>
        public static string MenuOverType {
            get {
                return ResourceManager.GetString("MenuOverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巡檢資料處理 的當地語系化字串。
        /// </summary>
        public static string MenuProcess {
            get {
                return ResourceManager.GetString("MenuProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product 的當地語系化字串。
        /// </summary>
        public static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MenuProductAlternative 的當地語系化字串。
        /// </summary>
        public static string MenuProductAlternative {
            get {
                return ResourceManager.GetString("MenuProductAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品圖片上傳 的當地語系化字串。
        /// </summary>
        public static string MenuProductImage {
            get {
                return ResourceManager.GetString("MenuProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase 的當地語系化字串。
        /// </summary>
        public static string MenuPurchase {
            get {
                return ResourceManager.GetString("MenuPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseInvoice 的當地語系化字串。
        /// </summary>
        public static string MenuPurchaseInvoice {
            get {
                return ResourceManager.GetString("MenuPurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quotation 的當地語系化字串。
        /// </summary>
        public static string MenuQuotation {
            get {
                return ResourceManager.GetString("MenuQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sales 的當地語系化字串。
        /// </summary>
        public static string MenuSales {
            get {
                return ResourceManager.GetString("MenuSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SalesInvoice 的當地語系化字串。
        /// </summary>
        public static string MenuSalesInvoice {
            get {
                return ResourceManager.GetString("MenuSalesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        public static string MenuSet {
            get {
                return ResourceManager.GetString("MenuSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人員報表 的當地語系化字串。
        /// </summary>
        public static string MenuStaffReport {
            get {
                return ResourceManager.GetString("MenuStaffReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StockChange 的當地語系化字串。
        /// </summary>
        public static string MenuStockChange {
            get {
                return ResourceManager.GetString("MenuStockChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Test 的當地語系化字串。
        /// </summary>
        public static string MenuTest {
            get {
                return ResourceManager.GetString("MenuTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 後續追蹤狀況設定 的當地語系化字串。
        /// </summary>
        public static string MenuTrack {
            get {
                return ResourceManager.GetString("MenuTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User 的當地語系化字串。
        /// </summary>
        public static string MenuUser {
            get {
                return ResourceManager.GetString("MenuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作崗位設定 的當地語系化字串。
        /// </summary>
        public static string MenuWorkplace {
            get {
                return ResourceManager.GetString("MenuWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已被使用改為停用!! 的當地語系化字串。
        /// </summary>
        public static string MessageChaneDelete2UpdateComplete {
            get {
                return ResourceManager.GetString("MessageChaneDelete2UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 完成!! 的當地語系化字串。
        /// </summary>
        public static string MessageChaneDelete2UpdateComplete2 {
            get {
                return ResourceManager.GetString("MessageChaneDelete2UpdateComplete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 完成!! 的當地語系化字串。
        /// </summary>
        public static string MessageComplete {
            get {
                return ResourceManager.GetString("MessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此資料有關連性,無法刪除!! 的當地語系化字串。
        /// </summary>
        public static string MessageDataHasLinking {
            get {
                return ResourceManager.GetString("MessageDataHasLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期格式錯誤!! 的當地語系化字串。
        /// </summary>
        public static string MessageDateTimeError {
            get {
                return ResourceManager.GetString("MessageDateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除資料，刪除後將無法復原資料!! 的當地語系化字串。
        /// </summary>
        public static string MessageDeleteConfirm {
            get {
                return ResourceManager.GetString("MessageDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無此工號，請確定輸入無誤!! 的當地語系化字串。
        /// </summary>
        public static string MessageEmployeeSearchError {
            get {
                return ResourceManager.GetString("MessageEmployeeSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回饋屬性為建議時，請選擇後續追蹤狀況!! 的當地語系化字串。
        /// </summary>
        public static string MessageFeedback2Error {
            get {
                return ResourceManager.GetString("MessageFeedback2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MessageLoginError 的當地語系化字串。
        /// </summary>
        public static string MessageLoginError {
            get {
                return ResourceManager.GetString("MessageLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料 的當地語系化字串。
        /// </summary>
        public static string MessageNoData {
            get {
                return ResourceManager.GetString("MessageNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工號{0}於日期{1}查無出差資料!!請確定您的日期正確或請聯絡人資部新增海外出差資料!! 的當地語系化字串。
        /// </summary>
        public static string MessageOverSeaNotYourData {
            get {
                return ResourceManager.GetString("MessageOverSeaNotYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先新增觀察構面資料!! 的當地語系化字串。
        /// </summary>
        public static string MessagePleaseCreateObservationFirst {
            get {
                return ResourceManager.GetString("MessagePleaseCreateObservationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先新增店別資料!! 的當地語系化字串。
        /// </summary>
        public static string MessagePleaseCreateStoreFirst {
            get {
                return ResourceManager.GetString("MessagePleaseCreateStoreFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確產品代碼!! 的當地語系化字串。
        /// </summary>
        public static string MessageProductIDError {
            get {
                return ResourceManager.GetString("MessageProductIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確使用者代碼!! 的當地語系化字串。
        /// </summary>
        public static string MessageUserIDError {
            get {
                return ResourceManager.GetString("MessageUserIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 消息編號 的當地語系化字串。
        /// </summary>
        public static string NewsID {
            get {
                return ResourceManager.GetString("NewsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 消息類別 的當地語系化字串。
        /// </summary>
        public static string NewsTypeID {
            get {
                return ResourceManager.GetString("NewsTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下月帳(每月__日) 的當地語系化字串。
        /// </summary>
        public static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string NQ_Sort {
            get {
                return ResourceManager.GetString("NQ_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人數 的當地語系化字串。
        /// </summary>
        public static string NQ_Sub_People {
            get {
                return ResourceManager.GetString("NQ_Sub_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計 的當地語系化字串。
        /// </summary>
        public static string NQ_Total_People {
            get {
                return ResourceManager.GetString("NQ_Total_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下架日期 的當地語系化字串。
        /// </summary>
        public static string OffDate {
            get {
                return ResourceManager.GetString("OffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到職日 的當地語系化字串。
        /// </summary>
        public static string OnboardDate {
            get {
                return ResourceManager.GetString("OnboardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第 {0} 筆 / 共 {1} 筆 的當地語系化字串。
        /// </summary>
        public static string PageCountAndCurrentLocationFormat {
            get {
                return ResourceManager.GetString("PageCountAndCurrentLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期已付金額 的當地語系化字串。
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 付款日期 的當地語系化字串。
        /// </summary>
        public static string PayDate {
            get {
                return ResourceManager.GetString("PayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期已付款金額合計 的當地語系化字串。
        /// </summary>
        public static string PaymentAmountTotal {
            get {
                return ResourceManager.GetString("PaymentAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用權限組別 的當地語系化字串。
        /// </summary>
        public static string PermissionID {
            get {
                return ResourceManager.GetString("PermissionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PostingTime 的當地語系化字串。
        /// </summary>
        public static string PostingTime {
            get {
                return ResourceManager.GetString("PostingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單價 的當地語系化字串。
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 價別 的當地語系化字串。
        /// </summary>
        public static string PriceKindID {
            get {
                return ResourceManager.GetString("PriceKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品代碼 的當地語系化字串。
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品圖片 的當地語系化字串。
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string ProductKindName {
            get {
                return ResourceManager.GetString("ProductKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱 的當地語系化字串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨數量 的當地語系化字串。
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨金額 的當地語系化字串。
        /// </summary>
        public static string PurchaseAmount {
            get {
                return ResourceManager.GetString("PurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨金額合計 的當地語系化字串。
        /// </summary>
        public static string PurchaseAmountTotal {
            get {
                return ResourceManager.GetString("PurchaseAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨日期 的當地語系化字串。
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨抵扣金額合計 的當地語系化字串。
        /// </summary>
        public static string PurchaseDeductTotal {
            get {
                return ResourceManager.GetString("PurchaseDeductTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨折讓金額合計 的當地語系化字串。
        /// </summary>
        public static string PurchaseDiscountTotal {
            get {
                return ResourceManager.GetString("PurchaseDiscountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨單編號 的當地語系化字串。
        /// </summary>
        public static string PurchaseID {
            get {
                return ResourceManager.GetString("PurchaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨稅額 的當地語系化字串。
        /// </summary>
        public static string PurchaseTax {
            get {
                return ResourceManager.GetString("PurchaseTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨稅額合計 的當地語系化字串。
        /// </summary>
        public static string PurchaseTaxTotal {
            get {
                return ResourceManager.GetString("PurchaseTaxTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計庫存量 的當地語系化字串。
        /// </summary>
        public static string QtyTotal {
            get {
                return ResourceManager.GetString("QtyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫-1 的當地語系化字串。
        /// </summary>
        public static string QtyWarehouse1 {
            get {
                return ResourceManager.GetString("QtyWarehouse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫-2 的當地語系化字串。
        /// </summary>
        public static string QtyWarehouse2 {
            get {
                return ResourceManager.GetString("QtyWarehouse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價日期 的當地語系化字串。
        /// </summary>
        public static string QuotationDate {
            get {
                return ResourceManager.GetString("QuotationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價單編號 的當地語系化字串。
        /// </summary>
        public static string QuotationID {
            get {
                return ResourceManager.GetString("QuotationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價授權等級 的當地語系化字串。
        /// </summary>
        public static string QuotationLevelID {
            get {
                return ResourceManager.GetString("QuotationLevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價人 的當地語系化字串。
        /// </summary>
        public static string QuotePerson {
            get {
                return ResourceManager.GetString("QuotePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排行 的當地語系化字串。
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實價 的當地語系化字串。
        /// </summary>
        public static string RealPrice {
            get {
                return ResourceManager.GetString("RealPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期已收款金額合計 的當地語系化字串。
        /// </summary>
        public static string ReceiptAmountTotal {
            get {
                return ResourceManager.GetString("ReceiptAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收款日期 的當地語系化字串。
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收款記錄編號 的當地語系化字串。
        /// </summary>
        public static string ReceiptID {
            get {
                return ResourceManager.GetString("ReceiptID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期已收金額 的當地語系化字串。
        /// </summary>
        public static string ReceivedAmount {
            get {
                return ResourceManager.GetString("ReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈日期 的當地語系化字串。
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預定到貨提醒(天數) 的當地語系化字串。
        /// </summary>
        public static string Remind {
            get {
                return ResourceManager.GetString("Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}AAA{1} 的當地語系化字串。
        /// </summary>
        public static string resourcekey {
            get {
                return ResourceManager.GetString("resourcekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核結果 的當地語系化字串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退回金額 的當地語系化字串。
        /// </summary>
        public static string ReturnAmount {
            get {
                return ResourceManager.GetString("ReturnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核日期 的當地語系化字串。
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安全存量 的當地語系化字串。
        /// </summary>
        public static string SafeStock {
            get {
                return ResourceManager.GetString("SafeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨數量 的當地語系化字串。
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨金額 的當地語系化字串。
        /// </summary>
        public static string SalesAmount {
            get {
                return ResourceManager.GetString("SalesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨金額合計 的當地語系化字串。
        /// </summary>
        public static string SalesAmountTotal {
            get {
                return ResourceManager.GetString("SalesAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售成本 的當地語系化字串。
        /// </summary>
        public static string SalesCost {
            get {
                return ResourceManager.GetString("SalesCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售日期 的當地語系化字串。
        /// </summary>
        public static string SalesDate {
            get {
                return ResourceManager.GetString("SalesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨抵扣金額合計 的當地語系化字串。
        /// </summary>
        public static string SalesDeductTotal {
            get {
                return ResourceManager.GetString("SalesDeductTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨折讓金額合計 的當地語系化字串。
        /// </summary>
        public static string SalesDiscountTotal {
            get {
                return ResourceManager.GetString("SalesDiscountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨單編號 的當地語系化字串。
        /// </summary>
        public static string SalesID {
            get {
                return ResourceManager.GetString("SalesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨稅額 的當地語系化字串。
        /// </summary>
        public static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷貨稅額 的當地語系化字串。
        /// </summary>
        public static string SalesTaxTotal {
            get {
                return ResourceManager.GetString("SalesTaxTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預定到貨日期 的當地語系化字串。
        /// </summary>
        public static string ScheduleDate {
            get {
                return ResourceManager.GetString("ScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SeqNo 的當地語系化字串。
        /// </summary>
        public static string SeqNo {
            get {
                return ResourceManager.GetString("SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 定價 的當地語系化字串。
        /// </summary>
        public static string SetPrice {
            get {
                return ResourceManager.GetString("SetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 置頂否 的當地語系化字串。
        /// </summary>
        public static string SetTop {
            get {
                return ResourceManager.GetString("SetTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出貨地址 的當地語系化字串。
        /// </summary>
        public static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運費 的當地語系化字串。
        /// </summary>
        public static string ShippingFee {
            get {
                return ResourceManager.GetString("ShippingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運送方式 的當地語系化字串。
        /// </summary>
        public static string ShippingModeID {
            get {
                return ResourceManager.GetString("ShippingModeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不足量 的當地語系化字串。
        /// </summary>
        public static string Shortage {
            get {
                return ResourceManager.GetString("Shortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不足量 的當地語系化字串。
        /// </summary>
        public static string Shortfall {
            get {
                return ResourceManager.GetString("Shortfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商簡稱 的當地語系化字串。
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 憑證單號 的當地語系化字串。
        /// </summary>
        public static string SourceID {
            get {
                return ResourceManager.GetString("SourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規格說明 的當地語系化字串。
        /// </summary>
        public static string SPEC {
            get {
                return ResourceManager.GetString("SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 票據狀況 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存數量 的當地語系化字串。
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存異動單號 的當地語系化字串。
        /// </summary>
        public static string StockChangeID {
            get {
                return ResourceManager.GetString("StockChangeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 託收/開立 的當地語系化字串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 直屬主管 的當地語系化字串。
        /// </summary>
        public static string SupervisorID {
            get {
                return ResourceManager.GetString("SupervisorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商 的當地語系化字串。
        /// </summary>
        public static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商名稱 的當地語系化字串。
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅額 的當地語系化字串。
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨款(未稅) 的當地語系化字串。
        /// </summary>
        public static string TaxExcluded {
            get {
                return ResourceManager.GetString("TaxExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號 的當地語系化字串。
        /// </summary>
        public static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票金額(已稅) 的當地語系化字串。
        /// </summary>
        public static string TaxIncluded {
            get {
                return ResourceManager.GetString("TaxIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課稅別 的當地語系化字串。
        /// </summary>
        public static string TaxLevelID {
            get {
                return ResourceManager.GetString("TaxLevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話 的當地語系化字串。
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話1 的當地語系化字串。
        /// </summary>
        public static string Telephone1 {
            get {
                return ResourceManager.GetString("Telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話2 的當地語系化字串。
        /// </summary>
        public static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string TestFalse {
            get {
                return ResourceManager.GetString("TestFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳款月份 的當地語系化字串。
        /// </summary>
        public static string TextAccountMonth {
            get {
                return ResourceManager.GetString("TextAccountMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理系統 的當地語系化字串。
        /// </summary>
        public static string TextAppName {
            get {
                return ResourceManager.GetString("TextAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期餘額 的當地語系化字串。
        /// </summary>
        public static string TextBalance {
            get {
                return ResourceManager.GetString("TextBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 託收(付款)銀行 的當地語系化字串。
        /// </summary>
        public static string TextBankAccount {
            get {
                return ResourceManager.GetString("TextBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生日次數 的當地語系化字串。
        /// </summary>
        public static string TextBirthdayCount {
            get {
                return ResourceManager.GetString("TextBirthdayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支票號碼 的當地語系化字串。
        /// </summary>
        public static string TextCheckNum {
            get {
                return ResourceManager.GetString("TextCheckNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 票據狀況 的當地語系化字串。
        /// </summary>
        public static string TextCheckStatus {
            get {
                return ResourceManager.GetString("TextCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分類方式 的當地語系化字串。
        /// </summary>
        public static string TextClassification {
            get {
                return ResourceManager.GetString("TextClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;copy; 2017 - 鼎泰豐小吃店股份有限公司 的當地語系化字串。
        /// </summary>
        public static string TextCompanyName {
            get {
                return ResourceManager.GetString("TextCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商編號 的當地語系化字串。
        /// </summary>
        public static string TextCompanyStartEnd {
            get {
                return ResourceManager.GetString("TextCompanyStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商類別 的當地語系化字串。
        /// </summary>
        public static string TextCompanyType {
            get {
                return ResourceManager.GetString("TextCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢條件： 的當地語系化字串。
        /// </summary>
        public static string TextCriteria {
            get {
                return ResourceManager.GetString("TextCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶編號 的當地語系化字串。
        /// </summary>
        public static string TextCustomerID {
            get {
                return ResourceManager.GetString("TextCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶編號 的當地語系化字串。
        /// </summary>
        public static string TextCustomerStartEnd {
            get {
                return ResourceManager.GetString("TextCustomerStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期區間 的當地語系化字串。
        /// </summary>
        public static string TextDateStartEnd {
            get {
                return ResourceManager.GetString("TextDateStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 託收/開立 的當地語系化字串。
        /// </summary>
        public static string TextDealItem {
            get {
                return ResourceManager.GetString("TextDealItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設 的當地語系化字串。
        /// </summary>
        public static string TextDefault {
            get {
                return ResourceManager.GetString("TextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 託收/開立 的當地語系化字串。
        /// </summary>
        public static string TextDepositSummary {
            get {
                return ResourceManager.GetString("TextDepositSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 迄 的當地語系化字串。
        /// </summary>
        public static string TextEnd {
            get {
                return ResourceManager.GetString("TextEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        public static string TextFunction {
            get {
                return ResourceManager.GetString("TextFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回大綱 的當地語系化字串。
        /// </summary>
        public static string TextGoTitle {
            get {
                return ResourceManager.GetString("TextGoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string TextiCount {
            get {
                return ResourceManager.GetString("TextiCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入 的當地語系化字串。
        /// </summary>
        public static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詢價日期 的當地語系化字串。
        /// </summary>
        public static string TextInquireDate {
            get {
                return ResourceManager.GetString("TextInquireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  巡店人員 的當地語系化字串。
        /// </summary>
        public static string TextInspectionPeople {
            get {
                return ResourceManager.GetString("TextInspectionPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已出發 的當地語系化字串。
        /// </summary>
        public static string TextIsGo {
            get {
                return ResourceManager.GetString("TextIsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已回國 的當地語系化字串。
        /// </summary>
        public static string TextIsIn {
            get {
                return ResourceManager.GetString("TextIsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未出發 的當地語系化字串。
        /// </summary>
        public static string TextIsNotGo {
            get {
                return ResourceManager.GetString("TextIsNotGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出差中 的當地語系化字串。
        /// </summary>
        public static string TextIsOut {
            get {
                return ResourceManager.GetString("TextIsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關鍵字 的當地語系化字串。
        /// </summary>
        public static string TextKeyWord {
            get {
                return ResourceManager.GetString("TextKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上期餘額 的當地語系化字串。
        /// </summary>
        public static string TextLastBalance {
            get {
                return ResourceManager.GetString("TextLastBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名 的當地語系化字串。
        /// </summary>
        public static string TextMing {
            get {
                return ResourceManager.GetString("TextMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 近一週生日人員 的當地語系化字串。
        /// </summary>
        public static string TextNearOneWeekBirthday {
            get {
                return ResourceManager.GetString("TextNearOneWeekBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 近兩月生日人員 的當地語系化字串。
        /// </summary>
        public static string TextNearTwoMonthBirthday {
            get {
                return ResourceManager.GetString("TextNearTwoMonthBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無資料 的當地語系化字串。
        /// </summary>
        public static string TextNoData {
            get {
                return ResourceManager.GetString("TextNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 筆 的當地語系化字串。
        /// </summary>
        public static string TextPen {
            get {
                return ResourceManager.GetString("TextPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入查詢條件 的當地語系化字串。
        /// </summary>
        public static string TextPleaseInput {
            get {
                return ResourceManager.GetString("TextPleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入過帳條件： 的當地語系化字串。
        /// </summary>
        public static string TextPostingYearMonth {
            get {
                return ResourceManager.GetString("TextPostingYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品類別 的當地語系化字串。
        /// </summary>
        public static string TextProductKind {
            get {
                return ResourceManager.GetString("TextProductKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱 的當地語系化字串。
        /// </summary>
        public static string TextProductName {
            get {
                return ResourceManager.GetString("TextProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品區間 的當地語系化字串。
        /// </summary>
        public static string TextProductStartEnd {
            get {
                return ResourceManager.GetString("TextProductStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string TextQty {
            get {
                return ResourceManager.GetString("TextQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收(開)票日期 的當地語系化字串。
        /// </summary>
        public static string TextReceiveDate {
            get {
                return ResourceManager.GetString("TextReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報告大綱 的當地語系化字串。
        /// </summary>
        public static string TextReportTitle {
            get {
                return ResourceManager.GetString("TextReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售日期 的當地語系化字串。
        /// </summary>
        public static string TextSalesDate {
            get {
                return ResourceManager.GetString("TextSalesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排列方式 的當地語系化字串。
        /// </summary>
        public static string TextSort {
            get {
                return ResourceManager.GetString("TextSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排列方式 的當地語系化字串。
        /// </summary>
        public static string TextSortOrder {
            get {
                return ResourceManager.GetString("TextSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起 的當地語系化字串。
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string TextStatus {
            get {
                return ResourceManager.GetString("TextStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商編號 的當地語系化字串。
        /// </summary>
        public static string TextSupplierID {
            get {
                return ResourceManager.GetString("TextSupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商名稱 的當地語系化字串。
        /// </summary>
        public static string TextSupplierName {
            get {
                return ResourceManager.GetString("TextSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組 的當地語系化字串。
        /// </summary>
        public static string TextTeam {
            get {
                return ResourceManager.GetString("TextTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單證類別 的當地語系化字串。
        /// </summary>
        public static string TextTicketType {
            get {
                return ResourceManager.GetString("TextTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 至 的當地語系化字串。
        /// </summary>
        public static string TextTo {
            get {
                return ResourceManager.GetString("TextTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳款總額 的當地語系化字串。
        /// </summary>
        public static string TextTotalAmount {
            get {
                return ResourceManager.GetString("TextTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計 的當地語系化字串。
        /// </summary>
        public static string TextTotalCount {
            get {
                return ResourceManager.GetString("TextTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string TextTrue {
            get {
                return ResourceManager.GetString("TextTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註：藍底表示：出差期間會遇到生日！ 的當地語系化字串。
        /// </summary>
        public static string TextUserRemark1 {
            get {
                return ResourceManager.GetString("TextUserRemark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫 的當地語系化字串。
        /// </summary>
        public static string TextWarehouse {
            get {
                return ResourceManager.GetString("TextWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫編號 的當地語系化字串。
        /// </summary>
        public static string TextWarehouseNo {
            get {
                return ResourceManager.GetString("TextWarehouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string TitleID {
            get {
                return ResourceManager.GetString("TitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總金額 的當地語系化字串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售總金額 的當地語系化字串。
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售總毛利 的當地語系化字串。
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售量 的當地語系化字串。
        /// </summary>
        public static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售總成本 的當地語系化字串。
        /// </summary>
        public static string TotalSalesCost {
            get {
                return ResourceManager.GetString("TotalSalesCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 調貨數量 的當地語系化字串。
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string UnitID {
            get {
                return ResourceManager.GetString("UnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員工編號 的當地語系化字串。
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員工姓名 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詢價單有效日期 的當地語系化字串。
        /// </summary>
        public static string ValidateDate {
            get {
                return ResourceManager.GetString("ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 憑證單號 的當地語系化字串。
        /// </summary>
        public static string VoucherID {
            get {
                return ResourceManager.GetString("VoucherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫編號 的當地語系化字串。
        /// </summary>
        public static string WarehouseID {
            get {
                return ResourceManager.GetString("WarehouseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原倉庫編號 的當地語系化字串。
        /// </summary>
        public static string WarehouseNewID {
            get {
                return ResourceManager.GetString("WarehouseNewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新倉庫編號 的當地語系化字串。
        /// </summary>
        public static string WarehouseOldID {
            get {
                return ResourceManager.GetString("WarehouseOldID", resourceCulture);
            }
        }
    }
}
