//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDeposit
    {
        public int SeqNo { get; set; }
        public string SourceID { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string CompanyID { get; set; }
        public string CheckNum { get; set; }
        public string BankID { get; set; }
        public string AccountID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public string CheckStatus { get; set; }
        public string Activate { get; set; }
        public string LastPerson { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
