//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquiry()
        {
            this.InquiryDetail = new HashSet<InquiryDetail>();
        }
    
        public string InquiryID { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public string CompanyID { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ValidateDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> Remind { get; set; }
        public string PurchaseID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Activate { get; set; }
        public string LastPerson { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryDetail> InquiryDetail { get; set; }
    }
}
