//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverSea
    {
        public int ID_OverSea { get; set; }
        public string CX_PID { get; set; }
        public string CX_Name { get; set; }
        public int ID_Country { get; set; }
        public string CX_From_Date { get; set; }
        public string CX_To_Date { get; set; }
        public int ID_OverType { get; set; }
        public string CX_Dept_Name { get; set; }
        public string CX_Dept_Name_Short { get; set; }
        public string CX_Title { get; set; }
        public string CX_OnBoard_Date { get; set; }
        public string CX_Birthday { get; set; }
        public string CX_OverSea_Remark { get; set; }
        public string CX_Place_Remark { get; set; }
        public bool FG_IsWorkCard { get; set; }
        public string CX_Create { get; set; }
        public System.DateTime DT_Create { get; set; }
        public string CX_Modify { get; set; }
        public Nullable<System.DateTime> DT_Modify { get; set; }
        public int NQ_MeetBirthday { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual OverType OverType { get; set; }
    }
}
