//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InquiryDetail = new HashSet<InquiryDetail>();
            this.PurchaseDetail = new HashSet<PurchaseDetail>();
            this.QuotationDetail = new HashSet<QuotationDetail>();
            this.StockChangeDetail = new HashSet<StockChangeDetail>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string KindID { get; set; }
        public string UnitID { get; set; }
        public string BrandID { get; set; }
        public Nullable<decimal> LatestCost { get; set; }
        public Nullable<decimal> SalesCost { get; set; }
        public Nullable<decimal> BizCost { get; set; }
        public string Linked { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> SetPrice { get; set; }
        public Nullable<decimal> RealPrice { get; set; }
        public string SPEC { get; set; }
        public string BOM { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> SafeStock { get; set; }
        public string Remarks { get; set; }
        public string Activate { get; set; }
        public string LastPerson { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryDetail> InquiryDetail { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockChangeDetail> StockChangeDetail { get; set; }
    }
}
