//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public string ReceiptID { get; set; }
        public string CustomerID { get; set; }
        public string AccountMonth { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CheckNum { get; set; }
        public Nullable<decimal> CheckAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public string Remarks { get; set; }
        public string Activate { get; set; }
        public string LastPerson { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Company Company { get; set; }
    }
}
