//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ReceivableSummary
    {
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string AccountMonth { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal SalesTax { get; set; }
        public decimal PurchaseAmount { get; set; }
        public decimal PurchaseTax { get; set; }
        public int ReceiptAmount { get; set; }
        public int SalesDeduct { get; set; }
        public int SalesDiscount { get; set; }
        public int PaymentAmount { get; set; }
        public int PurchaseDeduct { get; set; }
        public int PurchaseDiscount { get; set; }
        public decimal Remaining { get; set; }
        public Nullable<System.DateTime> AccountDate { get; set; }
        public decimal LastBalance { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
